"""empty message

Revision ID: 01e28d7afa46
Revises: 94be73a0b2af
Create Date: 2022-07-04 18:37:38.779462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e28d7afa46'
down_revision = '94be73a0b2af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_reports', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_reports', 'status')
    # ### end Alembic commands ###
